[project]
name = "institute-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "setuptools>=80.9.0",
    "pydantic-settings>=2.12.0",
    "fastapi>=0.127.0",
    "uvicorn>=0.40.0",
    "python-multipart>=0.0.21",
    "alembic>=1.17.2",
    "dotenv>=0.9.9",
    "aiomysql>=0.3.2",
    "cryptography>=46.0.5",
    "shared-auth-library",
    "requests>=2.32.5",
    "greenlet>=3.3.2",
]

[tool.uv.sources]
shared-auth-library = { path = "../../shared-auth-library" }
#shared-auth-library = { index = "gitlab" }

#[[tool.uv.index]]
#name = "gitlab"
#url = "https://gitlab-edu.supsi.ch/api/v4/projects/1401/packages/pypi/simple"
#authenticate = "always"