services:
  documents-mysql-db:
    image: mysql:8.4.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCUMENTS_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOCUMENTS_MYSQL_DATABASE}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DOCUMENTS_MYSQL_ROOT_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - documents-mysql-data:/var/lib/mysql

  chats-mysql-db:
    image: mysql:8.4.7
    ports:
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${CHATS_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${CHATS_MYSQL_DATABASE}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${CHATS_MYSQL_ROOT_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - chats-mysql-data:/var/lib/mysql

  inference-service:
    build:
      context: ../inference-service
      dockerfile: docker/Dockerfile
      args:
        ENV_PATH: .env.local
    environment:
      FRONTEND_URL: http://frontend:80
      MODEL_SERVICE_URL: http://model-service:8090
    restart: always
    ports:
      - "8095:8095"
    depends_on:
      model-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8095/api_inference/health" ]
      interval: 20s
      timeout: 5s
      retries: 10

  data-service:
    build:
      context: ../data-service
      dockerfile: docker/Dockerfile
      args:
        ENV_PATH: .env.local
    environment:
      ALEMBIC_SYNC_DATABASE_URL: mysql+pymysql://root:${MYSQL_ROOT_PASSWORD}@documents-mysql-db:3306/${MYSQL_DATABASE}
      DATABASE_URL: mysql+aiomysql://root:${MYSQL_ROOT_PASSWORD}@documents-mysql-db:3306/${MYSQL_DATABASE}
      DB_HOST: documents-mysql-db
      DB_PORT: 3306
      FRONTEND_URL: http://frontend:80
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      documents-mysql-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api_data/health" ]
      interval: 20s
      timeout: 5s
      retries: 10

  model-service:
    build:
      context: ../model-service
      dockerfile: docker/Dockerfile
      args:
        ENV_PATH: .env.local
    environment:
      FRONTEND_URL: http://frontend:80
    restart: always
    ports:
      - "8090:8090"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8090/api_model/health" ]
      interval: 20s
      timeout: 5s
      retries: 10
    volumes:
      - models-institute:/models

  frontend:
    build:
      context: ../frontend
      dockerfile: docker/Dockerfile
      args:
        NPM_TOKEN: ${GITLAB_TOKEN}
        ENV_PATH: .env.local
    environment:
      INFERENCE_SERVICE_URL: http://inference-service:8095
      DATA_SERVICE_URL: http://data-service:8080
      MODEL_SERVICE_URL: http://model-service:8090
      PORT: 80
    restart: always
    ports:
      - "80:80"
    depends_on:
      inference-service:
        condition: service_healthy
      data-service:
        condition: service_healthy
      model-service:
        condition: service_healthy

volumes:
  documents-mysql-data:
    driver: local
  chats-mysql-data:
    driver: local
  models-institute:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../models/institute