[project]
name = "shared-auth-library"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "setuptools>=80.9.0",
    "fastapi>=0.128.5",
    "pyjwt[crypto]>=2.11.0",
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools>=65.5.1", "wheel", "build"]
build-backend = "setuptools.build_meta"
