services:
  documents-mysql-db:
    image: mysql:8.4.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCUMENTS_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOCUMENTS_MYSQL_DATABASE}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DOCUMENTS_MYSQL_ROOT_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - documents-mysql-data:/var/lib/mysql
    networks:
      - internal

  chats-mysql-db:
    image: mysql:8.4.7
    ports:
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${CHATS_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${CHATS_MYSQL_DATABASE}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${CHATS_MYSQL_ROOT_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - chats-mysql-data:/var/lib/mysql
    networks:
      - internal

  inference-service:
    image: gitlab-edu.supsi.ch:5050/dti-isin/giuliano.gremlich/progetti_master/2025-2026/luca-fanto/decentralised-ai/institute/inference-service:${DOCKER_IMAGE_TAG}
    environment:
      INSTITUTE_NAME: ${INSTITUTE_NAME}
      KEYCLOAK_URL: ${KEYCLOAK_SERVICE_URL}
      KEYCLOAK_GLOBAL_HOSTNAME_URL: ${KEYCLOAK_SERVICE_URL}
      FRONTEND_URL: http://frontend:80
      MODEL_SERVICE_URL: http://model-service:8090
    restart: always
    ports:
      - "8095:8095"
    depends_on:
      model-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8095/api_inference/health" ]
      interval: 20s
      timeout: 5s
      retries: 10
    volumes:
      - models:/models-institute
    networks:
      - internal
      - external
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  data-service:
    image: gitlab-edu.supsi.ch:5050/dti-isin/giuliano.gremlich/progetti_master/2025-2026/luca-fanto/decentralised-ai/institute/data-service:${DOCKER_IMAGE_TAG}
    environment:
      INSTITUTE_NAME: ${INSTITUTE_NAME}
      KEYCLOAK_URL: ${KEYCLOAK_SERVICE_URL}
      KEYCLOAK_GLOBAL_HOSTNAME_URL: ${KEYCLOAK_SERVICE_URL}
      ALEMBIC_SYNC_DATABASE_URL: mysql+pymysql://root:${DOCUMENTS_MYSQL_ROOT_PASSWORD}@documents-mysql-db:3306/${DOCUMENTS_MYSQL_DATABASE}
      DATABASE_URL: mysql+aiomysql://root:${DOCUMENTS_MYSQL_ROOT_PASSWORD}@documents-mysql-db:3306/${DOCUMENTS_MYSQL_DATABASE}
      DB_HOST: documents-mysql-db
      DB_PORT: 3306
      FRONTEND_URL: http://frontend:80
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      documents-mysql-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api_data/health" ]
      interval: 20s
      timeout: 5s
      retries: 10
    networks:
      - internal
      - external

  model-service:
    image: gitlab-edu.supsi.ch:5050/dti-isin/giuliano.gremlich/progetti_master/2025-2026/luca-fanto/decentralised-ai/institute/model-service:${DOCKER_IMAGE_TAG}
    environment:
      INSTITUTE_NAME: ${INSTITUTE_NAME}
      KEYCLOAK_URL: ${KEYCLOAK_SERVICE_URL}
      KEYCLOAK_GLOBAL_HOSTNAME_URL: ${KEYCLOAK_SERVICE_URL}
      FRONTEND_URL: http://frontend:80
      MLFLOW_DEPARTMENT_SERVICE_URL: ${MLFLOW_DEPARTMENT_SERVICE_URL}
    restart: always
    ports:
      - "8090:8090"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8090/api_model/health" ]
      interval: 20s
      timeout: 5s
      retries: 10
    volumes:
      - models:/models-institute
    networks:
      - internal
      - external

  chat-service:
    image: gitlab-edu.supsi.ch:5050/dti-isin/giuliano.gremlich/progetti_master/2025-2026/luca-fanto/decentralised-ai/institute/chat-service:${DOCKER_IMAGE_TAG}
    environment:
      INSTITUTE_NAME: ${INSTITUTE_NAME}
      KEYCLOAK_URL: ${KEYCLOAK_SERVICE_URL}
      KEYCLOAK_GLOBAL_HOSTNAME_URL: ${KEYCLOAK_SERVICE_URL}
      INFERENCE_SERVICE_URL: http://inference-service:8095
      ALEMBIC_SYNC_DATABASE_URL: mysql+pymysql://root:${CHATS_MYSQL_ROOT_PASSWORD}@chats-mysql-db:3306/${CHATS_MYSQL_DATABASE}
      DATABASE_URL: mysql+aiomysql://root:${CHATS_MYSQL_ROOT_PASSWORD}@chats-mysql-db:3306/${CHATS_MYSQL_DATABASE}
      DB_HOST: chats-mysql-db
      DB_PORT: 3306
      FRONTEND_URL: http://frontend:80
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      chats-mysql-db:
        condition: service_healthy
      inference-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/api_chat/health" ]
      interval: 20s
      timeout: 5s
      retries: 10
    networks:
      - internal
      - external

  frontend:
    image: gitlab-edu.supsi.ch:5050/dti-isin/giuliano.gremlich/progetti_master/2025-2026/luca-fanto/decentralised-ai/institute/frontend:${DOCKER_IMAGE_TAG}
    environment:
      CHAT_SERVICE_URL: http://chat-service:8081
      DATA_SERVICE_URL: http://data-service:8080
      MODEL_SERVICE_URL: http://model-service:8090
      PORT: 80
    restart: always
    ports:
      - "80:80"
    depends_on:
      chat-service:
        condition: service_healthy
      data-service:
        condition: service_healthy
      model-service:
        condition: service_healthy
    networks:
      - internal
      - external

  supernode:
    image: flwr/supernode:1.25.0
    container_name: supernode
    environment:
      DATA_SERVICE_URL: http://data-service:8080
      MODEL_SERVICE_URL: http://model-service:8090
    ports:
      - "9094:9094"
    command:
      - --insecure
      - --superlink
      - ${SUPERLINK_SERVICE_URL}
      - --clientappio-api-address
      - 0.0.0.0:9094
      - --isolation
      - process
    depends_on:
      data-service:
        - condition: service_healthy
      model-service:
        - condition: service_healthy
    networks:
      - internal
      - external

  superexec-clientapp:
    image: gitlab-edu.supsi.ch:5050/dti-isin/giuliano.gremlich/progetti_master/2025-2026/luca-fanto/decentralised-ai/superexec:${DOCKER_IMAGE_TAG}
    container_name: superexec-clientapp
    environment:
      DATA_SERVICE_URL: http://data-service:8080
      MODEL_SERVICE_URL: http://model-service:8090
    command:
      - --insecure
      - --plugin-type
      - clientapp
      - --appio-api-address
      - supernode:9094
    stop_signal: SIGINT
    depends_on:
      - supernode
    volumes:
      - models:/models-institute
    networks:
      - internal
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

volumes:
  documents-mysql-data:
    driver: local
  chats-mysql-data:
    driver: local
  models:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MODELS_INTERNAL_PATH}

networks:
  internal:
    driver: bridge
    internal: true
  external:
    driver: bridge
    internal: false