[project]
name = "federated-learning-management-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "setuptools>=80.9.0",
    "pydantic-settings>=2.12.0",
    "fastapi>=0.127.0",
    "uvicorn>=0.40.0",
    "python-multipart>=0.0.21",
    "shared-auth-library",
]

[tool.uv.sources]
#shared-auth-library = { path = "../../institute/shared-auth-library" }
shared-auth-library = { index = "gitlab" }

[[tool.uv.index]]
name = "gitlab"
url = "https://gitlab-edu.supsi.ch/api/v4/projects/1401/packages/pypi/simple"
authenticate = "always"