[project]
name = "federated-learning-common-library"
version = "0.1.0"
description = "The common library of Federated Learning Service"
readme = "README.md"
requires-python = ">=3.12.12"
dependencies = [
    "setuptools>=80.9.0",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.12.0",
    "peft>=0.18.1",
    "torch>=2.9.1",
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools>=65.5.1", "wheel", "build"]
build-backend = "setuptools.build_meta"
