"""init tables

Revision ID: 5c54ba4e302f
Revises: 
Create Date: 2026-03-22 21:38:34.773448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c54ba4e302f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=25), nullable=False),
    sa.Column('deletable', sa.Boolean(), nullable=False),
    sa.Column('updatable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutes_name'), 'institutes', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_institutes_name'), table_name='institutes')
    op.drop_table('institutes')
    # ### end Alembic commands ###
