services:
  mysql-db:
    image: mysql:8.4.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: documents
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - internal

  inference-service:
    build:
      context: ../inference-service
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "9000:9000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/api_inference/health" ]
      interval: 20s
      timeout: 5s
      retries: 10
    networks:
      - internal

  data-service:
    build:
      context: ../data-service
      dockerfile: docker/Dockerfile
      args:
        ENV_PATH: .env.local
    environment:
      ALEMBIC_SYNC_DATABASE_URL: "mysql+pymysql://root:root@mysql-db:3306/documents"
      DATABASE_URL: "mysql+aiomysql://root:root@mysql-db:3306/documents"
      DB_HOST: "mysql-db"
      DB_PORT: "3306"
      FRONTEND_URL: "http://frontend:80"
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api_data/health" ]
      interval: 20s
      timeout: 5s
      retries: 10
    networks:
      - internal

  frontend:
    build:
      context: ../frontend
      dockerfile: docker/Dockerfile
      args:
        ENV_PATH: .env.local
    environment:
      INFERENCE_SERVICE_URL: http://inference-service:9000
      DATA_SERVICE_URL: http://data-service:8080
      PORT: 80
    restart: always
    ports:
      - "80:80"
    depends_on:
      inference-service:
        condition: service_healthy
      data-service:
        condition: service_healthy
    networks:
      - internal
      - external

volumes:
  mysql-data:
    driver: local

networks:
  internal:
    driver: bridge
  external:
    driver: bridge
    internal: false