services:
#  database:
#    image: mysql:8.4.7
#    container_name: pinkFlamingosContainer
#    ports:
#      - "3306:3306"
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=root
#    volumes:
#      - mysql:/data/db
#    networks:
#      - internal

  inference-service:
    build:
      context: ../inference-service
      dockerfile: docker/Dockerfile
    restart: always
    expose:
      - "9000:9000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/api_inference/health" ]
      interval: 20s
      timeout: 5s
      retries: 10
    networks:
      - internal

  data-service:
    build:
      context: ../data-service
      dockerfile: docker/Dockerfile
    restart: always
    expose:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api_data/health" ]
      interval: 20s
      timeout: 5s
      retries: 10
    networks:
      - internal

  frontend:
    build:
      context: ../frontend
      dockerfile: docker/Dockerfile
      args:
        ENV_PATH: .env.local
    environment:
      INFERENCE_SERVICE_URL: http://inference-service:9000
      DATA_SERVICE_URL: http://data-service:8080
      PORT: 80
    restart: always
    ports:
      - "80:80"
    depends_on:
      inference-service:
        condition: service_healthy
      data-service:
        condition: service_healthy
    networks:
      - internal
      - external

#volumes:
#  mysql:
#    driver: local

networks:
  internal:
    driver: bridge
  external:
    driver: bridge
    internal: false