services:
  institutes-mysql-db:
    image: mysql:8.4.7
    ports:
      - "33062:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${INSTITUTES_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${INSTITUTES_MYSQL_DATABASE}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${INSTITUTES_MYSQL_ROOT_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - institutes-mysql-data:/var/lib/mysql

  keycloak-postgres-db:
    image: postgres:15
    container_name: keycloak-postgres
    environment:
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $KEYCLOAK_POSTGRES_USER || exit 1" ]
      interval: 20s
      timeout: 5s
      retries: 10
    volumes:
      - keycloak-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.0
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres-db:5432/${KEYCLOAK_POSTGRES_DB}
      KC_DB_USERNAME: ${KEYCLOAK_POSTGRES_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}

      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

      KC_HTTP_PORT: 8085

      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
    ports:
      - "8085:8085"
    command:
      - start-dev
    depends_on:
      keycloak-postgres-db:
        condition: service_healthy

#  postgres:
#    image: postgres:15
#    container_name: mlflow-postgres
#    restart: always
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
#    ports:
#      - "5432:5432"
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER || exit 1"]
#      interval: 20s
#      timeout: 5s
#      retries: 10
#    volumes:
#      - mlflow-postgres-data:/var/lib/postgresql/data
#
#  minio:
#    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
#    container_name: mlflow-minio
#    restart: always
#    environment:
#      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
#      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
#    healthcheck:
#      test: [ "CMD", "mc", "ready", "local" ]
#      interval: 20s
#      timeout: 5s
#      retries: 10
#    command: server /data --console-address ":9001"
#    volumes:
#      - mlflow-minio-data:/data
#    ports:
#      - "9000:9000"
#      - "9001:9001"
#
#  minio_mc:
#    build:
#      context: ../minio
#      dockerfile: Dockerfile
#    depends_on:
#      minio:
#        condition: service_healthy
#    environment:
#      MINIO_SERVICE_URL: http://minio:9000
#      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
#      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
#      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
#      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
#
#  mlflow:
#    build:
#      context: ../mlflow
#      dockerfile: Dockerfile
#    container_name: mlflow-server
#    restart: always
#    environment:
#      MLFLOW_BACKEND_STORE_URI: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
#      MLFLOW_DEFAULT_ARTIFACT_ROOT: s3://flow-bucket
#      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
#      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
#      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
#    command: >
#      mlflow server
#      --host 0.0.0.0
#      --port 5000
#    ports:
#      - "5000:5000"
#    depends_on:
#      postgres:
#        condition: service_healthy
#      minio:
#        condition: service_healthy

volumes:
  institutes-mysql-data:
    driver: local
  keycloak-data:
    driver: local
#  mlflow-postgres-data:
#    driver: local
#  mlflow-minio-data:
#    driver: local