[project]
name = "federated-learning-client"
version = "0.1.0"
description = "The server app of Federated Learning Service"
readme = "README.md"
requires-python = ">=3.12.12"
dependencies = [
    "setuptools>=80.9.0",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.12.0",
    "flwr>=1.25.0",
    "peft>=0.18.1",
    "datasets>=4.4.2",
    "torch>=2.9.1",
    "federated-learning-common-library",
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

#[[tool.uv.index]]
#name = "gitlab"
#url = "https://gitlab-edu.supsi.ch/api/v4/projects/1401/packages/pypi/simple"
#authenticate = "always"
#cache-control = { api = "no-cache" }

[tool.uv.sources]
federated-learning-common-library = { path = "../../federated-learning-common-library" }

[build-system]
requires = ["setuptools>=65.5.1", "wheel", "build"]
build-backend = "setuptools.build_meta"
